version: '1.0'
services:
  postgres:
    image: postgres:14.5
    container_name: postgres_14_5
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=twitter
    ports:
      - 5432:5432
    volumes:
      - postgresqldata14:/var/lib/postgresql/data
  rabbitmq:
    image: rabbit-stomp-plugin:latest
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
      - 15674:15674
      - 61613:61613
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia
volumes:
  postgresqldata14:
  rabbitmq-data:
